name: Upgrade Requirements

on:
  schedule:
     - cron: "15 15 5/14 * *"
  workflow_dispatch:
     inputs:
       branch:
         description: 'Target branch to create requirements PR against'
         required: true
         default: 'master'
jobs:
   call-upgrade-python-requirements-workflow:
    with:
       branch: ${{ github.event.inputs.branch || 'master' }}
       email_address: masters-requirements-update@2u-internal.opsgenie.net
       send_success_notification: true
    secrets:
       requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
       requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
       edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
       edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
    uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@master
